### ISSUE TITLE
zlib.cydiar.com连不上啊，已经科学上网了

### ISSUE THREAD

**Issue by lopezycj** [lewangdev/bookbookgo_bot#1]
2023-04-14 11:41:52,482 - __main__ - INFO - User anji's input: 红楼梦
2023-04-14 11:41:52,485 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): zlib.cydiar.com:443
2023-04-14 11:41:52,831 - __main__ - ERROR - Exception while handling an update: Traceback (most recent call last):
  File "F:\my\bookbookgo_bot\.venv\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "F:\my\bookbookgo_bot\.venv\lib\site-packages\urllib3\connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "F:\my\bookbookgo_bot\.venv\lib\site-packages\urllib3\connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "F:\my\bookbookgo_bot\.venv\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "F:\my\bookbookgo_bot\.venv\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "I:\Python310\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "I:\Python310\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "I:\Python310\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\my\bookbookgo_bot\.venv\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "F:\my\bookbookgo_bot\.venv\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "F:\my\bookbookgo_bot\.venv\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='zlib.cydiar.com', port=443): Max retries exceeded with url: /search?query=title%3A%E7%BA%A2%E6%A5%BC%E6%A2%A6&limit=100 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))

**Comment by lewangdev** [comment]
@cydiar 大佬已经关掉 zlib.cydiar.com 了，也可能换了域名吧

可以自己用这个项目搭建 [book-searcher](https://github.com/book-searcher-org/book-searcher)，但是要自己构建一下书籍的索引了
